RESULT_CORRECT = "correct"
RESULT_INCORRECT = "incorrect"
RESULT_PENDING = "pending"

TEAM_TYPE_OFFICIAL = "official"
TEAM_TYPE_UNOFFICIAL = "unofficial"
TEAM_TYPE_GIRL = "girl"

TEAM_TYPE_ZH_CN_OFFICIAL = "正式队伍"
TEAM_TYPE_ZH_CH_UNOFFICIAL = "打星队伍"
TEAM_TYPE_ZH_CH_GIRL = "女队"
